### ISSUE TITLE
releases.nixos.org: dead links

### ISSUE THREAD

**Issue by asymmetric** [NixOS/nixos-homepage#476]
All the links I tried on https://releases.nixos.org/?prefix=nix (e.g. https://releases.nixos.org/releases.nixos.org/nix/nix-2.3/install) return `NoSuchKey`.

This S3 bucket is linked to from https://nixos.org/download.html

**Comment by asymmetric** [comment]
I guess it's because of the repeated `releases.nixos.org` in the URL.

**Comment by garbas** [comment]
oh true i didn't noticed this. thank you for discovering it.

**Comment by Profpatsch** [comment]
Looks like it was fixed?

**Comment by garbas** [comment]
Yes. I forgot to mention it in the PR

**Comment by rthadr** [comment]
Still seeing some of this, but it's easy enough to work around.  Example (click the link to the iso on the following page):

https://releases.nixos.org/?prefix=nixos/unstable-small/nixos-20.09pre242713.85afe9cbe9c/

**Comment by garbas** [comment]
oh i can see the problem. I fixed it but I'm not sure when the cache will clear

**Comment by rthadr** [comment]
Confirmed working
